gazebo_ros_control:
  pid_gains:
    # ====== 转向关节（舵向）: 稳定优先，P 不要大，D 稍微给一点阻尼 ======
    joint11: {p: 1000.0, i: 0.0, d: 5, i_clamp: 0.0}
    joint21: {p: 1000.0, i: 0.0, d: 5, i_clamp: 0.0}
    joint31: {p: 1000.0, i: 0.0, d: 5, i_clamp: 0.0}
    # ====== 轮子驱动（转速/位置控制都先用小 P + 一点 D 抑制抖动）======
    joint12: {p: 1.0, i: 0.0, d: 0.0}
    joint22: {p: 1.0, i: 0.0, d: 0.0}
    joint32: {p: 1.0, i: 0.0, d: 0.0}
    # ====== 转向关节（舵向）: 稳定优先，P 不要大，D 稍微给一点阻尼 ======
    joint13: {p: 1000.0, i: 0.01, d: 5, i_clamp: 0.1}
    joint23: {p: 1000.0, i: 0.01, d: 5, i_clamp: 0.1}
    joint33: {p: 1000.0, i: 0.01, d: 5, i_clamp: 0.1}

